### ISSUE TITLE
ERROR :(

### ISSUE THREAD

**Issue by IshwaranRudhara** [Krishna-Singhal/genStr#5]
![image](https://user-images.githubusercontent.com/39009926/111342180-3363cd00-86a0-11eb-9163-e9974bf0184f.png)

**Comment by Krishna-Singhal** [comment]
Now Try it will work

**Comment by IshwaranRudhara** [comment]
> Now Try it will work

THANKS!, can you able too see my logins? 2step pass?

**Comment by Krishna-Singhal** [comment]
> > Now Try it will work
> 
> THANKS!, can you able too see my logins? 2step pass?

No
